name: "Sample pipeline"

on:
    push:
        branches:
            - master
            - main

    pull_request:
        branches:
            - main
    
    workflow_dispatch:

jobs:
    sampleJob:
        runs-on: ubuntu-latest
        steps:
            - name: "print hello world"
              run: echo "hello world"

            - name: "print current working directory"
              run: pwd