name: "Sample pipeline"

on:
    push:
        branches:
            - master
            - main
    
    workflow_dispatch:

jobs:
    sampleJob:
        runs-on: ubuntu-latest
        steps:
            - name: "print hello world"
              run: echo "hello world"

            - name: "list files before downloading dependencies"
              run: ls

            - name: "Checkout code"
              uses: actions/checkout@v2
            
            - name: "Setup python env"
              uses: actions/setup-python@v2 
              with:
                  python-version: '3.x'

            - name: Install Python dependencies
              uses: py-actions/py-dependency-install@v4

            - name: "list files before downloading dependencies"
              run: ls

            - name: "run the python file"
              run: python scripts.py